# Generated by Django 5.0 on 2025-01-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamhrbusinessweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.TextField(default=5),
            preserve_default=False,
        ),
    ]
