# Generated by Django 5.1.5 on 2025-01-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamhrbusinessweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='description',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
